name: voynich_mobile
description: An app skeleton with good practies collected while building some apps at Voynich Data

version: 0.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.0.0+1
  intl: ^0.15.8
  collection: ^1.14.11
  table_calendar: ^2.2.2
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  provider: ^4.0.1
  cloud_firestore: 0.13.0+1
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  flutter_svg:
  flutter_form_builder: 3.7.2
  after_layout: 1.0.7+2
  image_picker: 0.6.3+1
  firebase_dynamic_links: ^0.5.0+9
  rxdart: ^0.23.1
  flutter_secure_storage: ^3.3.1+1
  package_info: ^0.4.0+13



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: any

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/


